### ISSUE TITLE
How to launch a vineyard cluster ?

### ISSUE THREAD

**Issue by Zarca** [alibaba/libvineyard#150]
Hi,
I'm puzzled about how the user can launch a vineyard cluster , Should i configure  and start the etcd cluster  firstly all 
by myself  ? 
Is there any step or configurations  i must pass to the libvineyard?

**Comment by sighingnow** [comment]
On kubernetes, I think you could launch a distributed vineyard cluster using helm, by following the instructions in README.

Without kubernetes, launching a vineyard cluster requires launch a etcd server first, then pass a `--etcd_endpoint` arguments to `vineyardd`. You could find all useful command line arguments by `vineyardd --help`.

Prebuilt vineyardd binary is available via Dockerhub [libvineyard/vineyardd](https://hub.docker.com/repository/docker/libvineyard/vineyardd). For linux users, a daily built standalone binary is available at  https://github.com/alibaba/libvineyard/releases/tag/latest.

**Comment by Zarca** [comment]
Hi, sighingnow
Actually, I'm using the vineyard without a kubernetes in deployment,
So, dose the etcd cluster play as a service registration for the vineyard's cluster,
and in the mean time, it also  keep the metadata of the vineyard instance ?

**Comment by sighingnow** [comment]
In vineyard etcd cluster play as a service registration (aka. vineyard instance registartion), as well as global metadata synchronization.

Most of the objects in vineyard are "local objects", which means the object may be need to visible for clients on other nodes. But for global objects, e.g., a distributed tensor or a paritioned graph, we sync the metadata to etcd and other vineyard server could see such objects by watching the change stream from etcd.

**Comment by Zarca** [comment]
Sorry, I did not get it , what's the difference between the global object and the local object?
it seems the latest doc only support C++ API on this type of global objects...

**Comment by sighingnow** [comment]
1. Local vs. Global object
   + Local objects are object whose blobs are all available on the local machine.
   + Global objects are object whose blobs cannot (or not) be fit in to a single machine, e.g., a large graph may be partitioned to many workers. Conceptly these fragments construct a graph.

   When sharing a graph between applications (e.g., different graph computation engines), you just need to share the graph (whose metadata contains graph schema, partition info, etc.), you don't need to shared a list of fragments, and an extra map to describe the partition info. The graph is a standalone object, a global object.

2. Without explicit migrate you cannot obtain data (here means blobs) from a remote vineyard server, since there's no RPC data accessing in vineyard. However you could still inspect the metadata, which could helpful for application to know to organized the next steps better (e.g., set a proper parallel threads number).

**Comment by Zarca** [comment]
Okay, i see. 
So the global object is just a set of distributed blobs across the cluster and be treated like a whole one conceptly,
This works when we can deploy parallel tasks without any data exchange among different nodes.
But in some cases, maybe the different nodes should exchange their own data (e.g. aggregation or group operations based on data's hash key ), will the communicator in the future release support it?

**Comment by sighingnow** [comment]
> maybe the different nodes should exchange their own data (e.g. aggregation or group operations based on data's hash key )

We choose to leave such stuffs to application itself, or at least drivers. You know, users may have many different options to shuffle their data, e.g., HTTP, tcp, RDMA, MPI, or other customized logic. They all have pros as well as cons in different environments and vineyard cannot fit all.

As the "aggregation or group operations based on data's hash key" won't be implmented in vineyard since vineyard itself is not a key-value storage. And, you konw, different users may want to hash on different part of the object with different hash functions, and then want to use different migration strategies after hashing. That is too application-specfic or problem-specific. Vineyard chooses to provide a pluggable design for users to implement and select such kind of drivers.
